version: '3.7'

services:
  nginx:
    image: nginx
    ports:
      - "80:80"

  redis:
    image: redis
    ports:
      - "6379:6379"

  node-exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8080:8080"  # Expose cAdvisor metrics on port 8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: unless-stopped
