global:
  scrape_interval: 5s  # Scrape every 15 seconds
  evaluation_interval: 5s  # Evaluate rules every 15 seconds

scrape_configs:
  # Scrape metrics from Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']  # Prometheus itself

  # Scrape metrics from the Infra VM
  - job_name: 'infra'
    static_configs:
      - targets: ['13.218.161.86:9100']  # Assuming Node Exporter is running on port 9100

  # Scrape metrics from the App VM
  - job_name: 'app'
    static_configs:
      - targets: ['3.95.223.163:9100']  # Assuming Node Exporter is running on port 9100

  - job_name: 'app_containers'
    static_configs:
      - targets: ['3.95.223.163:8080']

rule_files:
  - "alert-rules.yml"  # Include the alerting rules file here
